services:
  - type: web
    name: portfolio-backend
    env: docker
    dockerfilePath: ./backend/portfolio/Dockerfile
    envVars:
      - key: DB_HOST
        value: mysql-cpvm.railway.internal
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: wlmrUzZDHzaDpKozcjsLgMmwXDbVrYDJ
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: ALLOWED_ORIGINS
        value: https://portfolio-frontend.onrender.com,http://localhost:5173,http://localhost
      - key: PORT
        value: "8080"

  - type: web
    name: portfolio-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production